### ISSUE TITLE
Bug al mostrar la prioridad de la tarea

### ISSUE THREAD

**Issue by willingtonortiz** [evolucion-de-software-SI431-2001-WV61/angular-task-app#2]
https://github.com/evolucion-de-software-SI431-2001-WV61/angular-task-app/blob/8dbd47b418d827fa53a5f3c88636566260076e23/src/app/components/task/task.component.ts#L23

Queridos compañeros,
He encontrado un bug en el código de la tarea. En la función find se está haciendo una asignación en lugar de una comparación, por lo que la prioridad de las tareas se muestra de manera erronea.

Por favor corregir este error

**Comment by Ridaniel** [comment]
Ok Luigi lo revisara cuando pueda gracias

**Comment by LuiggiMS** [comment]
Se actualizó el código y así poder realizar correctamente la comparación.
